
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Wed Nov 06 03:32:05 CST 2024
//----------------------------------------------------

package codigo;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int articulo = 4;
  public static final int precio = 10;
  public static final int parC = 9;
  public static final int separador2 = 5;
  public static final int parA = 6;
  public static final int NombreP = 2;
  public static final int FIN_FORMULARIO = 12;
  public static final int Error = 11;
  public static final int EOF = 0;
  public static final int PuntoyComa = 8;
  public static final int CodigoP = 3;
  public static final int error = 1;
  public static final int numero2 = 7;
}

